theme: jekyll-theme-minimal

Homework Task 2 – Basics in R
Antonia Becker, Michelle Görlitz , Emilia Arens

Due: Thursday, May 2 by 08:59 CET

Instructions
Work together within your group.
Make sure you have R and RStudio installed. If you are an advanced user and aren’t using RStudio, make sure you have rmarkdown in order to ‘knit’ the HTML output.
Download this zip file. It contains an .Rmd file that you will edit and submit.
Open the .Rmd file in RStudio.
Fill in your names in the ‘author’ heading.
Fill in the required code and answers.
‘Knit’ the document (ctrl/cmd + shift + K in RStudio) to produce a HTML file.
Push both the files to your group’s Git repository before the deadline.
Using Github Pages, make a page that displays the knitted html file.
Suggested readings
R4DS (R for Data Science).
Required R packages
tidyverse (or ggplot2, dplyr, purrr, tibble)
set.seed(123) # this ensures that any psuedo-random computations are always the same
1. Installing and running R
a.
Your first task is simply to show that you have been able to install and run R and R Markdown. You don’t have to change this code, just uncomment it. Then the correct output will automatically appear when you ‘knit’ the document.

# UNCOMMENT THE CODE

R.version
##                _                           
## platform       x86_64-apple-darwin15.6.0   
## arch           x86_64                      
## os             darwin15.6.0                
## system         x86_64, darwin15.6.0        
## status                                     
## major          3                           
## minor          5.1                         
## year           2018                        
## month          07                          
## day            02                          
## svn rev        74947                       
## language       R                           
## version.string R version 3.5.1 (2018-07-02)
## nickname       Feather Spray
sessionInfo()
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-apple-darwin15.6.0 (64-bit)
## Running under: macOS  10.14.4
## 
## Matrix products: default
## BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
##  [5] tools_3.5.1     htmltools_0.3.6 yaml_2.2.0      Rcpp_1.0.1     
##  [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
## [13] digest_0.6.18   evaluate_0.12
Which version of R are you running? On which platform are you running it?

ANSWER:

R version 3.5.1 (2018-07-02) on x86_64-apple-darwin15.6.0

b.
Install the package tidyverse. Don’t install it in the code below. Instead, install it through the console. Then write code below to load the package and show the sessionInfo again.

# YOUR CODE HERE
library(tidyverse)
## ── Attaching packages ────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
## ✔ ggplot2 3.1.0     ✔ purrr   0.3.2
## ✔ tibble  1.4.2     ✔ dplyr   0.7.8
## ✔ tidyr   0.8.2     ✔ stringr 1.3.1
## ✔ readr   1.2.1     ✔ forcats 0.3.0
## Warning: package 'purrr' was built under R version 3.5.2
## ── Conflicts ───────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
sessionInfo("tidyverse")
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-apple-darwin15.6.0 (64-bit)
## Running under: macOS  10.14.4
## 
## Matrix products: default
## BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8
## 
## attached base packages:
## character(0)
## 
## other attached packages:
## [1] tidyverse_1.2.1
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.1       cellranger_1.1.0 pillar_1.3.0     compiler_3.5.1  
##  [5] plyr_1.8.4       bindr_0.1.1      methods_3.5.1    forcats_0.3.0   
##  [9] utils_3.5.1      tools_3.5.1      grDevices_3.5.1  digest_0.6.18   
## [13] lubridate_1.7.4  jsonlite_1.6     evaluate_0.12    tibble_1.4.2    
## [17] nlme_3.1-137     gtable_0.2.0     lattice_0.20-38  pkgconfig_2.0.2 
## [21] rlang_0.3.2      cli_1.0.1        rstudioapi_0.10  yaml_2.2.0      
## [25] haven_2.0.0      bindrcpp_0.2.2   withr_2.1.2      xml2_1.2.0      
## [29] httr_1.3.1       dplyr_0.7.8      stringr_1.3.1    knitr_1.20      
## [33] hms_0.4.2        graphics_3.5.1   datasets_3.5.1   stats_3.5.1     
## [37] rprojroot_1.3-2  grid_3.5.1       tidyselect_0.2.5 glue_1.3.1      
## [41] base_3.5.1       R6_2.4.0         readxl_1.1.0     rmarkdown_1.10  
## [45] readr_1.2.1      modelr_0.1.2     purrr_0.3.2      tidyr_0.8.2     
## [49] ggplot2_3.1.0    magrittr_1.5     backports_1.1.2  scales_1.0.0    
## [53] htmltools_0.3.6  rvest_0.3.2      assertthat_0.2.1 colorspace_1.3-2
## [57] stringi_1.2.4    lazyeval_0.2.1   munsell_0.5.0    broom_0.5.0     
## [61] crayon_1.3.4
Which version of tidyverse do you have installed?

ANSWER:

tidyverse_1.2.1

2. Tibbles (tidy tables)
The ToothGrowth data set comes with base R. You can read about this data set by running ?ToothGrowth in the console. It is a data frame. In this course, we prefer to use tibbles (tidy tables) instead of data frames.

a.
Convert the ToothGrowth data frame into a tibble using as_tibble(). Put this in a new variable called iris_tibble. Then print the tibble using the print() function.

# YOUR CODE HERE
tooth_growth_tibble <- as_tibble(ToothGrowth)
print(tooth_growth_tibble)
## # A tibble: 60 x 3
##      len supp   dose
##    <dbl> <fct> <dbl>
##  1   4.2 VC      0.5
##  2  11.5 VC      0.5
##  3   7.3 VC      0.5
##  4   5.8 VC      0.5
##  5   6.4 VC      0.5
##  6  10   VC      0.5
##  7  11.2 VC      0.5
##  8  11.2 VC      0.5
##  9   5.2 VC      0.5
## 10   7   VC      0.5
## # ... with 50 more rows
Which data type is the variable “supp”?

ANSWER:

It is a factor.

b.
Starting from the complete ToothGrowth data set, filter only the guinea pigs that were give orange juice.

# YOUR CODE HERE
tooth_growth_tibble_OJ <- filter(tooth_growth_tibble, supp == "OJ")
print(tooth_growth_tibble_OJ)
## # A tibble: 30 x 3
##      len supp   dose
##    <dbl> <fct> <dbl>
##  1  15.2 OJ      0.5
##  2  21.5 OJ      0.5
##  3  17.6 OJ      0.5
##  4   9.7 OJ      0.5
##  5  14.5 OJ      0.5
##  6  10   OJ      0.5
##  7   8.2 OJ      0.5
##  8   9.4 OJ      0.5
##  9  16.5 OJ      0.5
## 10   9.7 OJ      0.5
## # ... with 20 more rows
How many datapoints (i.e. guinea pigs) are left?

ANSWER:

30

c.
Starting from the complete ToothGrowth data set, filter only the guinea pigs that received ascorbic acid and had a dosage of 1.0mg or greater.

# YOUR CODE HERE
tooth_growth__AA_1 <- filter(tooth_growth_tibble, supp == "VC", dose >= 1.0)
print(tooth_growth__AA_1)
## # A tibble: 20 x 3
##      len supp   dose
##    <dbl> <fct> <dbl>
##  1  16.5 VC        1
##  2  16.5 VC        1
##  3  15.2 VC        1
##  4  17.3 VC        1
##  5  22.5 VC        1
##  6  17.3 VC        1
##  7  13.6 VC        1
##  8  14.5 VC        1
##  9  18.8 VC        1
## 10  15.5 VC        1
## 11  23.6 VC        2
## 12  18.5 VC        2
## 13  33.9 VC        2
## 14  25.5 VC        2
## 15  26.4 VC        2
## 16  32.5 VC        2
## 17  26.7 VC        2
## 18  21.5 VC        2
## 19  23.3 VC        2
## 20  29.5 VC        2
d.
Find out the mean length for the two supplement types. Do this with by piping tooth_growth_tibble to group_by() and then to summarise(). For instructions read the help page for summarise().

# YOUR CODE HERE
tooth_growth_tibble %>% 
  group_by(supp) %>% 
  summarise(
    mean_length = mean(len, na.rm = TRUE)
  )
## # A tibble: 2 x 2
##   supp  mean_length
##   <fct>       <dbl>
## 1 OJ           20.7
## 2 VC           17.0
What is the mean tooth length for guinea pigs that received Orange Juice?

ANSWER:

20,66333

3. Plotting data
a.
Using the ToothGrowth data set, create a plot of dose (x axis) against length (y axis) using ggplot(). Show the two supplement types in different colours.

# YOUR CODE HERE
ggplot(data = ToothGrowth) + 
  geom_point(mapping = aes(x = dose, y = len, color = supp))


After visually inspecting the graph, does there seem to be any difference between the types of supplement?

ANSWER:

The type of supplemet seems to influence the tooth groth since the supplement orange juice often leads to higher tooth growth values in contrast to the supplement vitamin C. This does not hold for dose = 2. Here we dicover opposite results.

End of homework sheet
